---
title: "ST-515_P9_Multivariate"
author: "payal jadhav"
date: "`r Sys.Date()`"
output: word_document
---

```{r}
library(readxl)
EXH_TABL <- read_excel("C:\\Users\\Payal\\Desktop\\St-515\\mcp\\rdk\\EXH_TABL.XLS")
View(EXH_TABL)
```

```{r}
N<-as.matrix(EXH_TABL[,1:5])
I<-nrow(N)
J<-ncol(N)
n<-sum(N)
P<-N/n
r<-rowSums(P)
c<-colSums(P)
Dr<-diag(r)
Dc<-diag(c)
Dr.inv<-diag(1/sqrt(r))
Dc.inv<-diag(1/sqrt(c))
S<-Dr.inv%*%(P-r%*%t(c))%*%Dc.inv
SVD<-svd(S)
U<-SVD$u;
V<-SVD$v;
sigma<-SVD$d
F_<-Dr.inv%*%U%*%sigma        #row coordinator
G_<-Dc.inv%*%V%*%sigma        #column coordinator

```

```{r}
# Row and column coordinates (Dimension 1)
F1 <- F_[,1]   # 10 row points
G1 <- G_[,1]   # 5 column points

# --- Biplot along 1D ---
plot(F1, rep(0, length(F1)),
     xlim = range(c(F1, G1)),
     ylim = c(-1, 1),  # just to leave space for labels
     pch = 19, col = "blue",
     xlab = "Dimension 1", ylab = "",
     yaxt = "n", main = "Biplot (1 Dimension)")

# Add row labels
text(F1, rep(0.2, length(F1)), labels = paste("Row", 1:length(F1)), col = "blue", pos = 3)

# Add column coordinates (as triangles)
points(G1, rep(-0.2, length(G1)), pch = 17, col = "red")

# Add column labels
text(G1, rep(-0.4, length(G1)), labels = paste("Col", 1:length(G1)), col = "red", pos = 1)


F1 <- F_[,1]; F2 <- F_[,2]
G1 <- G_[,1]; G2 <- G_[,2]

```
```{r}
# --- Your code until SVD ---
N <- as.matrix(EXH_TABL[,1:5])
I <- nrow(N)
J <- ncol(N)
n <- sum(N)
P <- N/n
r <- rowSums(P)
c <- colSums(P)
Dr <- diag(r)
Dc <- diag(c)
Dr.inv <- diag(1/sqrt(r))
Dc.inv <- diag(1/sqrt(c))
S <- Dr.inv %*% (P - r %*% t(c)) %*% Dc.inv
SVD <- svd(S)
U <- SVD$u
V <- SVD$v
sigma <- SVD$d
eig=sigma^2
inertia=sum(eig)
chi_sq=n*inertia
df=(I-1)*(J-1)
p_value=pchisq(chi_sq,df,lower.tail = F)

# --- Row & Column Coordinates (take 2 components) ---
F_ <- Dr.inv %*% U %*% diag(sigma)    # row coords
G_ <- Dc.inv %*% V %*% diag(sigma)    # col coords

# Take only first 2 dimensions
F1 <- F_[,1]
F2 <- F_[,2]
G1 <- G_[,1]
G2 <- G_[,2]

cat("inertia is",inertia)
cat("chi_sq is",chi_sq)
ifelse(p_value<0.05,"reject h0","we fail to reject h0")

```



```{r}
# --- Plot 2D biplot ---
plot(F1, F2,
     xlab = "Dimension 1", ylab = "Dimension 2",
     xlim = range(c(F1, G1)),
     ylim = range(c(F2, G2)),
     pch = 19, col = "blue", main = "CA Biplot (2 Components)")

# Add row labels
text(F1, F2, labels = paste("Row", 1:length(F1)), pos = 3, col = "blue")

# Add column coordinates as red arrows
arrows(0, 0, G1, G2, length = 0.1, col = "red")

# Add column labels
text(G1, G2, labels = paste("Col", 1:length(G1)), pos = 3, col = "red")
```
```{r}
# Extract first two dimensions
F12 <- F_[, 1:2]
G12 <- G_[, 1:2]

# Plot row points
plot(F12, 
     xlim = range(c(F12[,1], G12[,1])), 
     ylim = range(c(F12[,2], G12[,2])), 
     xlab = "Dimension 1", 
     ylab = "Dimension 2", 
     main = "Correspondence Analysis Biplot", 
     pch = 19, col = "blue")
column_N=c("A","B","C","D")
# Add row labels
text(F12[,1], F12[,2], labels = rownames(EXH_TABL), pos = 3, col = "blue")

# Add column points
points(G12[,1], G12[,2], pch = 17, col = "red")

# Add column labels
text(G12[,1], G12[,2], labels = column_N, pos = 3, col = "red")

# Add reference lines
abline(h = 0, v = 0, lty = 2, col = "gray")
```

